### ISSUE TITLE
Not able to execute factorial of 'linspace()'

### ISSUE THREAD

**Issue by Mashoodbhat** [JunoLab/atom-ink#101]
As I tried many a times to execute  the factorial of "linspace(0,n,m)" but failed. The system generates an error that factorial(linspace(......) has been moved to combinators and when I run Pkg.add("combinators") and installed to Julia but still I'm facing the same problem. Can you please let me know how to overcome this problem.
thank you.

**Comment by pfitzseb** [comment]
Please ask general Julia usage questions in the appropriate forum at https://discourse.julialang.org/. Thanks!

Your specific issue should be solved by `Pkg.add("Combinatorics")` to install the package and `using Combinatorics` to use it.

**Comment by Mashoodbhat** [comment]
I have used the same as u mentioned  Pkg.add("Combinatorics") but still I'm
not able to clear that error yet.
