### ISSUE TITLE
command history search via ^r key in the console?

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JunoLab/atom-ink#105]
If I invoke julia via terminal without using atom's console, I can search through my past command history by typing ^r. On the other hand, using the console in the atom editor, so far, I haven't find any way to search through my command history. Of course by typing "up arrow" key, I can see my immediate previous command, but often, I have to type many times to reach to the command I want to run again. I am wondering whether the atom's console has a capability of searching a specific command from the command history. (Of course, I do not want to open ~/.julia_history using some other editor to search a specific command).
Thanks for your help!
BVPs

**Comment by MikeInnes** [comment]
We don't have search per se right now. What we do is searching by the start of the command which will do the job most of the time; you can type e.g. the first letter of the command and press up to go through commands starting with that.

**Comment by BoundaryValueProblems** [comment]
Thanks a lot, MikeInnes. But when I type the first letter of the command, the list of all possible commands starting with that letter in various packages is shown, and not the list of the commands I used earlier in the session. Moreover, when I press the up key, it goes through that list of all possible commands starting with that letter, not the list of the command history. What should I do?

**Comment by MikeInnes** [comment]
What you're seeing is actually autocompletions rather than history. To see the history just press `esc` to get rid of the autocomplete and then press up.

**Comment by BoundaryValueProblems** [comment]
Thanks, MikeInnes! I didn't know that ```esc``` key trick!
