### ISSUE TITLE
A long command line in Console creates a slider that obscures the command

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JunoLab/atom-ink#106]
I posted this as https://github.com/JunoLab/atom-julia-client/issues/288, but it seems to me that atom-ink is more appropriate venue, so I am reposting it here:
When I type a long julia command in a Console pane, it automatically creates a slider for convenience. However, the command line width does not change even if the slider is created. Consequently, the actual long command line is partially obscured by the slider. How can we resolve this problem?
Thanks a lot for your help!
BVPs

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-ink/commit/8395174ba7a4e102cf350a84e33e0d8c9c44171c (until a new version is out, you can enable `Soft Wrap` in Atom's Editor settings). Thanks for reminding me of this again :)
