### ISSUE TITLE
Deprecated selector in `ink/styles/console.less`

### ISSUE THREAD

**Issue by canimus** [JunoLab/atom-ink#110]
In `ink/styles/console.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `ink-console atom-text-editor::shadow .cursor-line` => `ink-console atom-text-editor.editor .cursor-line`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by pfitzseb** [comment]
Fixed by https://github.com/JunoLab/atom-ink/commit/56f9c1719c9c516878e657a22382d5224e42ec0e.
