### ISSUE TITLE
Deprecated selector in `ink/styles/ink.less`

### ISSUE THREAD

**Issue by AzamatB** [JunoLab/atom-ink#111]
In `ink/styles/ink.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow div.block-notify .region` => `atom-text-editor.editor div.block-notify .region`

* `atom-text-editor::shadow div.block-notify.hidden .region` => `atom-text-editor.editor div.block-notify.syntax--hidden .region`

* `atom-text-editor::shadow div.doc-highlight .region` => `atom-text-editor.editor div.doc-highlight .region`

* `atom-text-editor::shadow div.ink.block` => `atom-text-editor.editor div.syntax--ink.syntax--block`

* `atom-text-editor::shadow div.ink.block.hidden` => `atom-text-editor.editor div.syntax--ink.syntax--block.syntax--hidden`

* `atom-text-editor::shadow .highlight.error-line .region` => `atom-text-editor.editor .highlight.error-line .region`

* `atom-text-editor::shadow .icon::before` => `atom-text-editor.editor .icon::before`

* `atom-text-editor::shadow .icon-diff-modified::before` => `atom-text-editor.editor .icon-diff-modified::before`

* `atom-text-editor::shadow .icon-chevron-right::before` => `atom-text-editor.editor .icon-chevron-right::before`

* `atom-text-editor::shadow .ink-bp` => `atom-text-editor.editor .ink-bp`

* `atom-text-editor::shadow .ink-bp.ink-hide` => `atom-text-editor.editor .ink-bp.ink-hide`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-ink/commit/56f9c1719c9c516878e657a22382d5224e42ec0e.
