### ISSUE TITLE
Plot does not fit the plot pane

### ISSUE THREAD

**Issue by DatName** [JunoLab/atom-ink#119]
After update to 0.6.3 I am getting strange behavior of plot pane. When I do
`Gadfly.plot(x = [1 2 3], y = [1 2 3])`
I get the following:
![juno_plot_pane](https://cloud.githubusercontent.com/assets/3992719/22928192/32939ae4-f2c6-11e6-9755-a38b5f433f01.PNG)
But then I execute
`Plots.plot(x = [1 2 3], y = [1 2 3])`
**twice**  which gives me a normal plot that fits the plot pane. But still, If I resize console, the plot pane dos not resizes accordingly:

![juno_plot_pane_1](https://cloud.githubusercontent.com/assets/3992719/22928304/cb110b8a-f2c6-11e6-8c64-e21e1aa23b33.PNG)

Finally, if I execute these two lines one after another: 
`Gadfly.plot(x = [1 2 3], y = [1 2 3])`
`Plots.plot(x = [1 2 3], y = [1 2 3])`
the plot will change its size dramatically every time. 

julia-client: v.0.5.12
Plots uses PyPlot backend
all packages are up-to-date
Running this under Windows

**Comment by pfitzseb** [comment]
This should be fixed on the latest release, provided the backend properly queries the plot pane size (Plots.jl for example works).
Please reopen if this isn't fixed.
