### ISSUE TITLE
Setting to control width of pane showing errors?

### ISSUE THREAD

**Issue by penntaylor** [JunoLab/atom-ink#120]
Errors that pop up in inline panes often require horizontal scrolling, making them hard to make sense of. Is there an existing way to set the default width of these panes?

Example of error pane requiring scrolling:

![ink_error_pane](https://cloud.githubusercontent.com/assets/6378937/23188593/e096c1aa-f854-11e6-9561-24d9c69bb5e1.png)

**Comment by pfitzseb** [comment]
I suppose you could just overwrite the relevant css yourself. Inline results really need an overhaul though...

**Comment by pfitzseb** [comment]
In case you wanna try: In [this](https://github.com/JunoLab/atom-ink/tree/sp/newrsults) branch, the results will automatically fill all remaining space in the editor.

**Comment by pfitzseb** [comment]
Alright, this is fixed on master. :)
