### ISSUE TITLE
Command history in Console via up arrow key does not work!

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JunoLab/atom-ink#123]
I just updated Atom to version 1.14.4 and atom-ink to 0.6.4.
Now, the command history in Console using up arrow key does not work properly anymore regardless on Mac, Windows, Linux. On the other hand, if I run julia via terminal REPL, the command history via up arrow key still works nicely. What's wrong here? How can I use the up arrow key to get proper command history.
Thanks for your help!
BVPs

**Comment by mindonly** [comment]
I can confirm this symptom.  just updated to atom 1.14.4 and atom-ink 0.6.4 on osx and console history doesn't work as it did before.  pressing up in Console gives 1-2 previous commands at most, and default configuration value is 10000

**Comment by mindonly** [comment]
with the ink 0.6.5 update this issue appears to be fixed, thanks!

**Comment by MikeInnes** [comment]
Great, let me know if there's any further issue.
