### ISSUE TITLE
Support line-break in the middle of a sentence

### ISSUE THREAD

**Issue by Datseris** [JunoLab/atom-ink#129]
While typing at the console window (I am not talking about the editor window) in Atom, using Ctrl+Enter inserts a new line. However, it only inserts the new line at the *end of the line*. I would like this to happen at the cursor location, so that this:
```
for stuff
```
can become this:
```

for stuff
```
Or, equivalently, this:
```
pos, vel = f()
```
can become this:
```
pos,
vel = f()
```

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-julia-client/commit/c2f476649d647cde82ac5b48bbcf324999ceed8f.

[Sorry for making you create the issue (and in the wrong place even), but I didn't think it'd be *that* easy...]

**Comment by Datseris** [comment]
How can a man be so fast.
