### ISSUE TITLE
Any text in terminal pane causes entire atom UI to be slow.

### ISSUE THREAD

**Issue by ry-dgel** [JunoLab/atom-ink#145]
Using juno in atom 1.18.0 on macOS.

Any time there is text present in the terminal pane, all of atom become sluggish, scrolling and typing have significant delays. The autocomplete popup also becomes exceptionally slow. The problem gets worse the more text is in the terminal but instantly goes away if the terminal is cleared.

**Comment by pfitzseb** [comment]
Should be fixed with the new REPL implementation.
