### ISSUE TITLE
TextEditor.editorElement is deprecated.

### ISSUE THREAD

**Issue by AzamatB** [JunoLab/atom-ink#146]
`TextEditor.prototype.editorElement` has always been private, but now
it is gone. Reading the `editorElement` property still returns a
reference to the editor element but this field will be removed in a
later version of Atom, so we recommend using the `element` property instead.
```
TextEditor.editorElement (<embedded>:2383:20)
_loop (/Users/Azamat/.atom/packages/ink/lib/editor/result.js:351:35)
listener (/Users/Azamat/.atom/packages/ink/lib/editor/result.js:362:22)
```

**Comment by pfitzseb** [comment]
Fixed on master.

**Comment by minyoungrho** [comment]
I have done Pkg.checkout("Atom"), and updated Atom to master. However, the depreciation warning sign has not gone away.

**Comment by pfitzseb** [comment]
On `atom-ink` master. Just wait for the next release and you should be good to go :)
