### ISSUE TITLE
`ctrl+c` shortcut key is not working on console

### ISSUE THREAD

**Issue by YongHee-Kim** [JunoLab/atom-ink#149]
![copyfail2](https://user-images.githubusercontent.com/7087745/30360104-52dfbd5e-988a-11e7-864c-5d82100e6e18.gif)

Default keymap for `ctrl-c` is not working on my PC since a few days ago. 
I'm on newest version for `Atom` and `Ink`
>OS: Windows (x86_64-w64-mingw32)
>[Atom 1.20.0](https://github.com/atom/atom/releases/tag/v1.20.0)
>[Ink 0.7.5](https://github.com/JunoLab/atom-ink/releases/tag/v0.7.5)

Editing `...\\ink\\keymaps\\ink.cson` fixed this issue for me
``` cson
'.platform-win32 .ink, .platform-linux .ink':
  # 'ctrl-c': 'native!'
  'ctrl-c': 'core:copy'
```

**Comment by pfitzseb** [comment]
You probably can just get rid of that entry all together. I'll tag a patch release for that in a week.
