### ISSUE TITLE
inline results stealing focus

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/atom-ink#150]
Some time relatively recently (maybe in the past 2 months or so?) I noticed that sometimes when using atom-julia-client, my keyboard input would stop working. It took me a while to catch the pattern, but I think what's happening is that if I click on an inline result (say to expand it, then re-contract it) my key presses aren't registered by the editor window until I click on it again.

My best guess is that when I click on the inline result it's stealing keyboard focus. I'm not sure if this is an Atom issue or an Ink issue. Looking at the DOM in the inspector doesn't show any changes when I click between the inline result and the editor, so I'm not sure where that focus is handled.

**Comment by marius311** [comment]
Was just about to post about this exact issue when I found this one. Indeed, it feels like its started sometime in the last few months, and unfortunately is quite annoying. 

I'm seeing this with atom/1.23.1, atom-julia-client/0.6.6, and ink/0.7.11.

**Comment by pfitzseb** [comment]
I think this was a semi-intentional change, but I agree that it is pretty annoying.
