### ISSUE TITLE
Autocompletion might be overenthusiastic

### ISSUE THREAD

**Issue by jebej** [JunoLab/atom-ink#156]
I find that the autocompletion is generally overenthusiastic at providing suggestions, and it has been bugging me for a while now. It seems that it should at least wait for two characters to have been typed before starting to suggest anything.

Particularly annoying is the 3->ternary substitution, which I regularly trigger by too quickly hitting the enter key.

I'm sure people have different preferences, and wanted to start a conversation.

**Comment by pfitzseb** [comment]
Do note that you can adjust most of these things under `Settings > Packages > autocomplete-plus`. 
I'd really recommend you to use this option:
![grafik](https://user-images.githubusercontent.com/6735977/33688550-11345d62-dadc-11e7-836a-6db690b17176.png)
You can also set the minimum word length etc there.
