### ISSUE TITLE
Console appears frozen on first start

### ISSUE THREAD

**Issue by JonnyCBB** [JunoLab/atom-ink#168]
When I first open a Julia console using `Cmd-J Cmd-O` I get the following screen:

![screen shot 2018-07-26 at 12 45 06](https://user-images.githubusercontent.com/7965372/43260545-c1fd55bc-90d1-11e8-82c7-a629535b3705.png)

I can see that Julia has started in the debugging console:

![screen shot 2018-07-26 at 12 45 54](https://user-images.githubusercontent.com/7965372/43260604-e0cc7df6-90d1-11e8-8c88-983f6859221a.png)

However, the console is frozen and I can't type anything in. I have to close the Julia console and reopen it and then it works as expected (not frozen, I see this screen and I can interact and type and evaluate things as expected: 

![screen shot 2018-07-26 at 12 47 27](https://user-images.githubusercontent.com/7965372/43260717-2e36bf66-90d2-11e8-9927-289ceec0577b.png)

Although this bug isn't the end of the world it is slightly annoying. Is there a fix for this?

**Versions**
OS: Mac High Sierra v10.13.6
Atom: 1.28.2
Julia: 0.7.0-beta2
Julia-client: 0.7.1
Ink: 0.9.1

**Comment by pfitzseb** [comment]
I've never seen that one before -- can you try enabling the `Fallback Renderer` setting in the julia-client options, close the REPL and restart Atom?

Edit: Actually, can you also expand the `> Object` part in the `No deserializer found` warning above? Might be related to that.

**Comment by JonnyCBB** [comment]
So there's good news and bad news
- **Good news**: When I enable the `Fallback Renderer` the console works as expected first time 👍  so it solves the problems.

- **Bad news (well maybe not so bad)**: When I turn the `Fallback Renderer` off the problem persists but the `No deserializer found` warning is no longer there. I'm not sure why

I'm happy to close this issue if you are with the solution - *enable the `Fallback Renderer` option in the julia-client settings*
