### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by nhavt** [JunoLab/atom-ink#179]
Could someone please help me with the following error? Thanks in advance!

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.0 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Education
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.9.8

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At C:\Users\nhavt\.atom\packages\ink\node_modules\xterm\lib\Linkifier.js:140

TypeError: Cannot read property '0' of undefined
    at Linkifier._doLinkifyRow (/packages/ink/node_modules/xterm/lib/Linkifier.js:140:24)
    at Linkifier._linkifyRow (/packages/ink/node_modules/xterm/lib/Linkifier.js:126:18)
    at Linkifier._linkifyRows (/packages/ink/node_modules/xterm/lib/Linkifier.js:54:18)
    at /packages/ink/node_modules/xterm/lib/Linkifier.js:49:69
```

### Commands

```
     -3:03.3.0 core:confirm (textarea.xterm-helper-textarea)
     -2:18.3.0 julia-client:open-a-repl (input.hidden-input)
  2x -1:33.4.0 julia-client:run-file (button.btn.icon.enablement.icon-playback-play)
```

### Non-Core Packages

```
atom-beautify 0.33.2 
atom-material-ui 2.1.3 
autocomplete-paths 2.12.2 
autocomplete-python 1.10.12 
busy-signal 1.4.3 
document-outline 2.1.2 
expose 0.15.0 
file-icons 2.1.25 
git-blame 1.7.0 
git-plus 8.1.0 
git-time-machine 2.1.0 
goto-definition 1.3.4 
highlight-selected 0.14.0 
ide-python 1.0.0 
indent-detective 0.3.0 
ink 0.9.8 
intentions 1.1.5 
julia-client 0.7.7 
language-julia 0.17.0 
latex-completions 0.3.5 
linter 2.2.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
open-recent 5.0.0 
pane-layout-plus 0.7.4 
project-manager 3.3.6 
split-diff 1.5.2 
symbols-tree-view 0.14.0 
todo-show 2.3.2 
tool-bar 1.1.10 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment]
That's an upstream issue which should be fixed with the next version of xterm.js, which should be out soonish (I thope). I'll release a new ink version ASAP after that.

**Comment by nhavt** [comment]
Thanks for looking at this issue.

**Comment by dlfivefifty** [comment]
Is there anyway to turn off the uncaught exception messages? It makes it unusable.

**Comment by pfitzseb** [comment]
Wait, does this open the Atom console even when you're not running Atom in dev mode?

**Comment by AndreaNeumayr** [comment]
I have the same problems. I open the Atom console (in my case the Julia repl). I get this message after dragging and changing the size of the Julia Repl Window.

**Comment by pfitzseb** [comment]
Alright, I've reverted back to a xterm.js version that doesn't show this bug, so please update to ink 0.9.10.
