### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by mauricioszabo** [JunoLab/atom-ink#19]
This is more a documentation request than an issue...

I'm trying to use your package, but there's not a single documentation. As I know it's hard to document these things,I would suggest some example code or something like this, so newcomers would know where to start.

You could, for example, add a "stub data" for each GIFs in the README.

**Comment by pfitzseb** [comment]
The one big example for using ink is the [julia-client](https://github.com/JunoLab/atom-julia-client), from which all the examples are taken as well.

You might want to have a look at [eval.coffee](https://github.com/JunoLab/atom-julia-client/blob/master/lib/eval.coffee) and the [console stuff](https://github.com/JunoLab/atom-julia-client/blob/master/lib/ui/console.coffee). 

Still, an official API and docs would be great but kinda unlikely at this time. When there's the first stable version of `atom-julia-client` and we have implemented all we need for that, then hopefully someone finds the time to write something up. 

If there are any specific questions, feel free to ask!

**Comment by MikeInnes** [comment]
I added some docs for the console to the docs folder in this repo. This is obviously a WIP, if there are particular features that you're interested in let me know so I can prioritise!

**Comment by mauricioszabo** [comment]
Currently I'm able to find my way around documentartion, so I think it is already solved. Thanks!
