### ISSUE TITLE
Better console

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/atom-ink#20]
The console, as it is implemented now, behaves radically different from what one might expect from a normal REPL. This is pretty much only related to the buffering -- after 10ms, we create a new cell. This messes up newlines and all sorts of stuff, obviously.

Suggestion:
- Buffer for 10ms or longer.
- If there's a `\n` in the string-to-be-printed, split it into the array `cells`.
- `cells[0]` is appended to the last cell, if and only if it is of the same type as the current write request.
- `cells[1:end]` are printed as their own cells.

I am working on implementing this, but don't have all that much time right now -- this issue is only so that I don't forget what I wanted to do ;) (or someone else wants to do it). The naive implementation is quite easy btw, but what we want is better performance (and also https://github.com/JunoLab/atom-ink/pull/14) so we can prevent issues like https://github.com/JunoLab/atom-julia-client/issues/54.

**Comment by MikeInnes** [comment]
Definitely agree we need something like this. I was thinking along similar lines – we really want to display all output immediately, and attach it to the last cell if it appears quickly enough. The time-before-new-cell can be higher if there's no newline as well.

We'll probably also want to implement some sort of virtualised scrolling at some point so we can store a lot more output.

The other thing that would be really nice is to detect when a chunk of output is getting huge and display only a small portion of it. Expanding it then opens it in a real Atom buffer.

**Comment by pfitzseb** [comment]
No, I don't think we want to only append to the last cell if it appears quickly enough -- that'd be radically different from a normal REPL implementation. Consider for example something like 

```
while bla
  do_some_slow_stuff()  
  print(".")
end
println("\ndone")
```

every `.` should be appended to the previous cell, no matter how slow `do_some_slow_stuff()` is. I'd like to only get a new cell if the `type` of the next output is different from the last cell's type or a newline is encountered. Cell content would also wrap, but that wouldn't create a new cell.

I don't really like using `timeout`s, because there's no guarantee about when they are executed -- in theory, Atom could just hang because something takes way to much time. 

I did [implement a protoype](https://github.com/JunoLab/atom-ink/tree/va-fasterconsoleproto) that kinda behaves how I want it to and should be more or less en par with the julia REPL in terms of performance [1] -- it's very ugly code though (don't look at it for too long...) and input and a few other things are not working correctly. If we want to go this way, a bit of a redesign of `view.coffee` is in order, methinks ;)

Also, I really like the idea of using an Atom buffer -- it might actually be the smarter (and faster) choice to just dump content directly into one instead of rolling our own console design. The input could be realized with a underline decoration containing in `mini-editor` and our fancy results should Just Work anyways.

## 

[1] benchmark:

```
for i = 1:100_000
  print(i)
  i % 10 == 0 && println()
end
```

For me, this takes something like 4 seconds in Atom and approx. ten times that in the REPL. This of course is not really fair because I'm buffering for a very long time and not scrolling, but whatever ;)

Also, this is much slower than the current implemntation for that benchmark, which kinda defeats the point. But still, I think this is more correct behaviour. I will probably have to rethink the "each line in a new cell" approach, even though I really like it.

**Comment by MikeInnes** [comment]
We can play around with different behaviours, I suppose, but personally I quite like that if you call – for example – `@time foo()` followed by `versioninfo()` from a buffer, you get clearly delineated output in the console, which makes things much more readable when the outputs aren't separated by the inputs themselves (as in a regular repl).

I think it would be fair to class stuff like the `do_some_slow_stuff` case as a terminal-ism which we don't have to support – any more than we need to support ASCII control codes. We have much nicer ways to do things like displaying progress, taking input etc., so we can specialise the console for displaying output and results and not worry too much about the rest. If someone particularly wants terminal-like behaviour they can always use a terminal ;)

**Comment by pfitzseb** [comment]
Alright. But would you really want to start a new cell solely because of the time elapsed between the last and the current call? That just seems so wrong to me ;)

Also, we can't really expect the terminal-isms to go away, just because most packages will be developed for the REPL. So either we implement those functionalities in a generic way in `Base` or close to it and hook into the display mechanisms, e.g. provide a generic `progressbar(disp, fraction)` function that prints the dot-thing I described above when called with `progressbar(REPL(), 0.5)` or as something more fancy when called as `progressbar(Juno(), 0.5)`. Or we provide at least rudimentary support for the terminal-isms and have output work just like one would expect it to -- only create a linebreak when there's a `\n` and not based on time.

Just out of curiosity: What are the "much nicer ways to do things like displaying progress, taking input"?

**Comment by MikeInnes** [comment]
Yeah, I think that kind of design will be the right way forward. It would be strange to support all kinds of output backends for plots and things only to be completely limited when it comes to things like progress bars, especially when we can largely reuse the same machinery for both.

We already have quite a nice way to select options via the `Atom.select([...])` function, and we can prompt for free-form input via the terminal. My plan for progress bars is to have a ProgressMeter.jl-like API that displays a progress bar in Atom's status bar – which will be a bit nicer than printing dots ;)
