### ISSUE TITLE
Uncaught Error: No option with key "cursorWidth"

### ISSUE THREAD

**Issue by takuizum** [JunoLab/atom-ink#257]
Hi guys!

After updating atom julia-client and ink, I cannot use Juno.
I try reinstalling them, but the trouble is not resolved.

Could you tell me some advice or suggestions to solve it?

### My environment is below.

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: WIn 10
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.12.0

### Stack Trace

Uncaught Error: No option with key "cursorWidth"

```
At C:\Users\bc0089985\.atom\packages\ink\node_modules\xterm\lib\xterm.js:1

Error: No option with key "cursorWidth"
    at e.getOption (/packages/ink/node_modules/xterm/lib/xterm.js:1:228264)
    at e.getOption (/packages/ink/node_modules/xterm/lib/xterm.js:1:56024)
    at e._renderBarCursor (/packages/ink/node_modules/xterm-addon-webgl/lib/xterm-addon-webgl.js:1:46489)
    at e._render (/packages/ink/node_modules/xterm-addon-webgl/lib/xterm-addon-webgl.js:1:45917)
    at e.onGridChanged (/packages/ink/node_modules/xterm-addon-webgl/lib/xterm-addon-webgl.js:1:44734)
    at /packages/ink/node_modules/xterm-addon-webgl/lib/xterm-addon-webgl.js:1:20316
    at Array.forEach (<anonymous>)
    at e.renderRows (/packages/ink/node_modules/xterm-addon-webgl/lib/xterm-addon-webgl.js:1:20287)
    at t._renderRows (/packages/ink/node_modules/xterm/lib/xterm.js:1:223483)
    at e._renderCallback (/packages/ink/node_modules/xterm/lib/xterm.js:1:221801)
    at e._innerRefresh (/packages/ink/node_modules/xterm/lib/xterm.js:1:49596)
    at /packages/ink/node_modules/xterm/lib/xterm.js:1:49365
```
### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-language-r 1.4.8 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-monokai 0.10.9 
busy-signal 2.0.1 
file-icons 2.1.39 
highlight-selected 0.17.0 
ide-r 0.1.8 
indent-detective 0.4.0 
ink 0.12.0 
intentions 1.1.5 
julia-client 0.12.0 
language-julia 0.19.2 
language-stan 1.2.0 
language-weave 0.6.7 
latex-completions 0.3.6 
linter 2.3.1 
linter-julia 0.8.3 
linter-ui-default 1.8.1 
Lucario 2.2.0 
markdown-preview-plus 3.11.5 
markdown-table-formatter 2.9.2 
mathjax-wrapper 0.1.0 
save-workspace 0.5.0 
script 3.25.0 
styri-syntax 1.0.0 
tool-bar 1.2.0 
uber-juno 0.3.0 
```

**Comment by pfitzseb** [comment]
Can you close all terminals and restart Juno again? That should fix the issue since the current code doesn't reference `cursorWidth` at any point.

If that doesn't help, try going to `Edit -> Preferences -> Packages -> julia-client` and changing the `Terminal Renderer` setting to `canvas` or `dom` and restart again:
![image](https://user-images.githubusercontent.com/6735977/74636807-0bd2c600-5169-11ea-9c67-2a1d85641f9e.png)

**Comment by takuizum** [comment]
Thanks for replying. @pfitzseb 

I closed them and restart Juno again, but the error was not be fixed.
However, changing the terminal renderer to `canvas` fixed this issue!

For a while, I'm using this setting. Thanks a lot!

**Comment by matteorossini** [comment]
Just another workaround: if you prefer to stick to `webgl`, you can go to `Edit -> Preferences -> Packages -> julia-client` and change the value of `Terminal Options -> Cursor Style` setting to `block` or `underline`.

**Comment by pfitzseb** [comment]
Good catch, thanks! The underlying issue should be fixed by [this PR](https://github.com/JunoLab/atom-ink/pull/258), so the next release will support the bar cursor with the webgl backend.
