### ISSUE TITLE
Console results' font size not adjustable on the fly

### ISSUE THREAD

**Issue by mkborregaard** [JunoLab/atom-ink#36]
In the newest master of the atom-ink console, the font has become very large - it seems like the setting linking this to the global font size setting in Atom has slipped somehow.

**Comment by MikeInnes** [comment]
Could you post a screenshot? Recently I did change console results to use the editor, rather than UI, font settings.

**Comment by mkborregaard** [comment]
Sure, here you are: https://drive.google.com/file/d/0BwWjA0Ez4iLhY3BoeWdoTkwxbFU/view?usp=sharing

It is the orange text I would like to have smaller

**Comment by MikeInnes** [comment]
Great, thanks for the shot. Hopefully this will be fixed when we release 0.4, and if not I'll take another look at it.

**Comment by mkborregaard** [comment]
Thanks!

**Comment by stakaz** [comment]
Hello, I would like to say, that this issue is still present in the 0.4.1 version with Atom 1.6. Would be great to have a setting parameter to manually set the font size. Or at least have the same font size as the editor has. For now the font size remains constant and a way to big independently of wether I increase or decrease the font size in the editor. Thanks.

**Comment by pfitzseb** [comment]
The problem here is that we only set the font size of results when initializing `ink`. Try restarting Atom and you should have a consistent font size everywhere.

**Comment by stakaz** [comment]
You are right. But this is a bad behaviour.
1. I cannot increase or decrease the font in the console during a session. E.g. when I print out a long table, I sometimes need a smaller font and so on.
2. When I increase the font in the editor, on next startup the font in the console gets increased, too.
3. I would like to have a separate parameter for the console to be able to use different font sizes for editor and console.
4. I think, this is another bug in Atom itself. But when I use 12pt font size, the font size in console is ok but the font size in editor is much smaller than a 12pt font should be. Have anyone an idea, what is going on here?

**Comment by pfitzseb** [comment]
I agree, the current behaviour isn't all that great, I'll rename the issue.

Regarding the fourth point: Try pressing `Ctrl`+`0` when you have the editor focused -- you may have zoom out of it by doing something like `Ctrl`+`-` or `Ctrl`+`MouseWheel`.

**Comment by stakaz** [comment]
Thats a good idea. No, it was not an issue with the zoom...

**Comment by pfitzseb** [comment]
Fixed by 4fb2a5ac0b35fe2e9c111816cb7b4801bfee5b85.
