### ISSUE TITLE
Ink doesn't change color of f\prime<tab>(x) when in unicode

### ISSUE THREAD

**Issue by ssingleton** [JunoLab/atom-ink#42]
I found a surprising, and otherwise insignificant, inconsistency:

![image](https://cloud.githubusercontent.com/assets/7118968/13931158/51efee10-efa2-11e5-8371-a7385a5a0be8.png)

The f\prime<tab>(x) does not change colors despite other unicode functions doing so. This holds when the prime is applied to other letters, include other unicode such as \alpha. 

Perhaps there is a reason for this? Given most of my work is differential equations and first order conditions, it would be easier to read my code if f\prime<tab>(x) did display as other functions do.

**Comment by MikeInnes** [comment]
cc @spencerlyon2, I think this is an issue with atom-language-julia. I guess the prime symbol doesn't come in under the unicode `alpha` category used by the grammar's regexes, but I'm not sure what it does come under.

**Comment by sglyon** [comment]
Yes definitely a problem for over there instead of ink.

I'm not sure why `\prime` doesn't fall in that category and other unicode like `\epsilon\tilde` and `\eta\_0` do.

**Comment by ssingleton** [comment]
Thank you for taking this to atom-language-julia, Spencer. and, thank you for your quick replies, both of you!
