### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by PeterBocan** [JunoLab/atom-ink#49]
Hello guys, this has jumped at me after the update to the latest version. (Atom suggested to report it to you.)

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.3
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package, v0.4.3
### Stack Trace

Uncaught TypeError: Cannot read property 'toString' of undefined

```
At /Users/pb/.atom/packages/ink/lib/editor/spinner.coffee:94

TypeError: Cannot read property 'toString' of undefined
    at ReadFileContext.callback (/Users/pb/.atom/packages/ink/lib/editor/spinner.coffee:94:27)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
```
### Commands

```
     -1:17.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:51.2.0 julia-client:start-julia (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:40.2.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
ink, v0.4.3
julia-client, v0.4.4
language-julia, v0.6.0
latex-completions, v0.3.1

# Dev
No dev packages
```

**Comment by pfitzseb** [comment]
Does this still occur after restarting Atom? 
My best guess is that something went awry in the update process, but since the error's from a file that doesn't exit after the update, it shouldn't be permanent or anything.

**Comment by PeterBocan** [comment]
After restarting Atom it has requested to open julia in terminal and update packages (Pkg.update) and after next restart it has recompiled everything and works properly. Probably some minor issue.

**Comment by pfitzseb** [comment]
Alright, glad it's working for you!
I'll close this.
