### ISSUE TITLE
Cannot find module './util/views'

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/atom-ink#53]
I get this error when trying to load ink

**Comment by pfitzseb** [comment]
Are you on master? If so, are you on the latest commit? If not, then something's wrong, because that file doesn't exist in the latest release _and_ isn't required anywhere...

**Comment by dlfivefifty** [comment]
Yep I’m on master for both ink and julia-client, and I’m still getting the error

**Comment by MikeInnes** [comment]
Nope this is my fault, I added views.coffee on the workspace branch and then used it on the master branch :)

**Comment by MikeInnes** [comment]
Should be fixed if you pull again.

**Comment by dlfivefifty** [comment]
Yep, fixed!
