### ISSUE TITLE
Console Improvements

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/atom-ink#54]
- [x] Remember size and position (to the left, downwards etc.) when closing and reopening the console (https://github.com/JunoLab/atom-julia-client/issues/172).
- [ ] Make console undockable (https://github.com/JunoLab/atom-julia-client/issues/180) and remember that as well.
- [ ] Only start a new cell on linebreak, but still buffer and append to last cell if types match. If we can implement this in a somewhat performant manner, we'll have  much better REPL compatibility. Still can't overwrite stuff, but still.
- [x] Make the results' content selectable (and copyable).

**Comment by MikeInnes** [comment]
Do we have a reasonable path to implementing the un-docking stuff? It seems to me like this basically involves implementing the feature in general for Atom; we'd need to figure out how it should work for general panes, move over CSS and keybindings and so on. I have another potential solution for the julia-client issue but will mention it there.

**Comment by MikeInnes** [comment]
> Still can't overwrite stuff, but still.

At the moment I basically see interpreting console control codes as a total non-goal, not least because the use cases (e.g. progress bars) are things we can do better graphically. Is that way off base?

**Comment by pfitzseb** [comment]
Well, I thought about opening a new Electron window and connecting that to the Julia server once we have that (and the server then "broadcasts" `STDOUT` to all clients or something like that) -- didn't think about the dependencies though...

About the console stuff: Yeah, I agree, we shouldn't jump through too many hoops. I'm mostly just annoyed with not being able to print pretty stuff to the console because I get funky linebreaks everywhere.
On a related note: That hack in julia-client where you hide the `require(Symbol)` method overwrite doesn't work for me, because that line gets split into multiple cells on my machine :D

**Comment by MikeInnes** [comment]
Oh yeah, well handling STDOUT is yet another issue to think about...

So the newline stuff is still affecting you quite badly then? It's been working great for me, but yeah I guess we do need an approach for that.

**Comment by pfitzseb** [comment]
![console](https://cloud.githubusercontent.com/assets/6735977/15520909/f30d5588-2208-11e6-8c61-229905df98d4.PNG)
Yup ;)

**Comment by petertuuk** [comment]
I'll bump the multi-window support topic. With Julia 0.6 and then 1.0 coming, updates to the UI could be well-timed for return on investment.

**Comment by jmboehm** [comment]
I would prefer the line in the console where one enters text to be 'separate' from the output (in other words, it should remain visible when I scroll up). That way one does not always need to scroll down to type a new command. Of course tastes may differ.
