### ISSUE TITLE
ink.Result error block not as error rendered

### ISSUE THREAD

**Issue by carocad** [JunoLab/atom-ink#64]
After creating an ink.Result object with  error: true, type: 'block' I expected it to be displayed underline with red font. The result is in fact displayed underline but not with red font.

On the other hand if I put the ink.Result as inline + error, the result is correctly displayed with red ink and to the right of the specified line.

I guess there must be a point where the the red font is invalidated by the block CSS properties

**Comment by pfitzseb** [comment]
Should be fixed by [this](https://github.com/JunoLab/atom-ink/commit/bf390719b41df82a8607ec3df782ceca241d3ced), but I didn't test it (so it'd be great if you could do that and close this issue if everything works alright).

**Comment by carocad** [comment]
hey @pfitzseb thanks for the quick reply.
I'm new to atom so I'm not really sure how can I test this change when there is yet not an ink release. I am using ink as a consumed service so I guess I'm trapped by the released versions.

If you know a way that I can test this please let me know and I will check it out.

**Comment by MikeInnes** [comment]
@carocad This should be as simple as uninstalling your current copy of ink and running

```
apm install https://github.com/JunoLab/atom-ink
```

to get the git master version. If you at some point need to release proto-repl but are relying on newer ink features, we can cut a release for you.
