### ISSUE TITLE
Ink was installed - But consistent message installation requirement displayed

### ISSUE THREAD

**Issue by duytrung** [JunoLab/atom-ink#65]
Hi,

I installed Juno and dependencies in Atom. But it displayed a message saying that Ink is missing and required installation from setting tab.

Please fix this.

Thanks 

TN

**Comment by MikeInnes** [comment]
Can I see a screenshot of your installed packages as well as of the error message? How did you install the packages, and in what order? Did you try restarting atom?

Unfortunately we can't fix this without reproducing it, so we will need more information.

**Comment by pfitzseb** [comment]
Should you still have this issue with the latest version of Juno, please ask for help over at discuss.junolab.org.
