### ISSUE TITLE
Auto scroll does not (always) work with the ink console

### ISSUE THREAD

**Issue by carocad** [JunoLab/atom-ink#66]
see jasongilman/proto-repl#140
This bug was recently found with the new ink console for proto-repl. I was able to reproduce it using the steps described in the original post.

Is this because the input is multi-line?

**Comment by jasongilman** [comment]
I'm pretty sure that's the cause as well.

**Comment by MikeInnes** [comment]
Yes, the console has to explicitly scroll everything up when there's new input – that logic is [here](https://github.com/JunoLab/atom-ink/blob/0150f89bf3d5b049b2e704ff3b5e24d1becacffa/lib/console/view.coffee#L190-L199). In principle it's just a case of applying that same logic when input is pasted in and when enter is pressed.

**Comment by pfitzseb** [comment]
I'm trying to fix this, but the really generic case isn't all that easy -- in principle we want to scroll to the bottom whenever `items` changes it's height, e.g. when a `Tree` inside a result cell is expanded.

**Comment by MikeInnes** [comment]
Handling the really general case would be nice but probably isn't as crucial – if you're expanding trees then you probably want to scroll anyway, and it's easier to do because you have your hand on the mouse.

**Comment by jasongilman** [comment]
If I have an instance of a console how could I make it scroll to the bottom via a method call? I'm looking for a short term work around.

**Comment by MikeInnes** [comment]
Haven't tried it, but you should be able to modify the `atom.views.getView(console).scrollTop` to your liking – just setting it to infinity or something should do what you want.

**Comment by carocad** [comment]
@jasongilman I am no longer sure if this is an ink's console bug. If I write a multiline code on the console:

```
(+
   1
   1)
```

and then the console command: `evaluate` it correctly scrolls to the bottom.

Nevertheless if I send the same code for evaluation from a clojure editor to the console, then the ink console doesn't automatically scrolls.

That might indicate that the error is on our side but I guess we need more testing for that

**Comment by pfitzseb** [comment]
I'm pretty sure this is a problem with ink. 
Can you try the patch in my PR above (which should be strictly better than the current implementation) and see if that fixes it?
