### ISSUE TITLE
Inline results - changes in tree, difficult to see results

### ISSUE THREAD

**Issue by mauricioszabo** [JunoLab/atom-ink#69]
Hello, in the master branch (the one I'm using to make a PR for Ink) I've seen that inline results that contains trees became more difficult to read. This is some code, in Clojure, with the old tree:

![image](https://cloud.githubusercontent.com/assets/138037/17741237/d55481f0-6471-11e6-8171-da506357f749.png)

and with the new one: notice as values get pushed to the end of list, and it's _very difficult_ to inspect then:

![image](https://cloud.githubusercontent.com/assets/138037/17741689/8d125974-6473-11e6-8d3e-5c6d68ee9639.png)

Can we, at least, get a configuration parameter to decide which one to use? I need to use huge maps and vectors in Clojure, and with this new tree view it's completely unusable.

**Comment by pfitzseb** [comment]
Strange -- this looks good for me:
![trees](https://cloud.githubusercontent.com/assets/6735977/17744431/e681aab2-64a7-11e6-96ec-6ff3dba8b956.PNG)

Do you have some custom css for your results or something like that?

**Comment by jasongilman** [comment]
This might be a problem from the Proto REPL side. I forked the Atom ink tree code in Proto REPL at first to improve performance and then to offer some new capabilities like buttons in the tree. I did not attempt to push that back to Atom ink. It's still using the styling from the Atom ink package though.

**Comment by pfitzseb** [comment]
Our tree view code has [changed a bit](https://github.com/JunoLab/atom-ink/blob/master/lib/tree.coffee) since then, so maybe that causes a mismatch between the css and the dom?

**Comment by mauricioszabo** [comment]
Well, I've created these screenshots opening Atom with the master version of Ink and proto-repl, and then checking out the 4.0.0 tag of Ink and opening another Atom instance with it, so no stylesheet issues nor any changes on proto-repl version.

**Comment by pfitzseb** [comment]
I'm relatively sure your issue happens because of [this](https://github.com/JunoLab/atom-ink/blob/b2ec7c5937a372ea39af943e5528e396d0997f93/styles/ink.less#L215) line -- can you try deleting that? 

Not quite sure why it doesn't cause any issues for me though...

**Comment by mauricioszabo** [comment]
Yes, that worked fine. Deleting the line corrects the tree layout.

**Comment by pfitzseb** [comment]
Great, now we only need to find out why it's there (@MikeInnes) and why it's not causing any problems for us but breaks proto-repl ;)

**Comment by jasongilman** [comment]
I fixed the problem within Proto REPL. Would you be interested in getting the updated tree view pushed back to Ink from Proto REPL? https://github.com/jasongilman/proto-repl/blob/master/lib/tree-view.coffee#L56 It adds the ability to optionally display buttons like in the following picture:

<img width="895" alt="demo_clj_ _src_ __users_jason_work_github_workspace_proto-repl-demo" src="https://cloud.githubusercontent.com/assets/192983/17834848/47021bf8-6721-11e6-951e-27f41a016382.png">

I use the buttons to allow interaction with inline values that were displayed. Proto REPL can capture all the values from the middle of an algorithm. The added buttons allow the user to "def"  one or more of the captured values (define a var with the same name as a local binding) so they can try executing some of the code to help debug an issue. 

The buttons that are added can be of any name and used for any particular purpose.

**Comment by MikeInnes** [comment]
The change is there so that we can display tuples like this:

<img width="419" alt="screenshot 2016-08-23 22 51 02" src="https://cloud.githubusercontent.com/assets/2234614/17911202/492d8ee8-6984-11e6-8ad2-8dd614f52b17.png">

IIRC the fix is just to have an extra div around things that need to be on their own line, but sounds like it's been figured out on proto's end anyway.

@jasongilman thanks a lot for the offer! I'll take a look at the code and we can figure out what makes sense. As an immediate question, do you think it's possible to implement this by passing appropriate HTML into the tree view rather than by modifying tree-view.coffee itself? Also, how does it interact with horizontally-nested views like the above?

**Comment by pfitzseb** [comment]
I'll close this, since the original problem is fixed. Upstraming proto-repls modified code can be discussed in a separate issue (or even PR, if someone's up for it :)).
