### ISSUE TITLE
Function.extractParams is deprecated.

### ISSUE THREAD

**Issue by carocad** [JunoLab/atom-ink#70]
I got this from my ink development package. There are also some warnings regarding the use of some css classes.

==== AUTO GENERATED TEXT ======
Assigning custom properties to a marker when creating/copying it is
deprecated. Please, consider storing the custom properties you need in
some other object in your package, keyed by the marker's id property.

```
Function.extractParams (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:43:14)
MarkerLayer.markRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:196:71)
DisplayMarkerLayer.markBufferRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:90:62)
TextEditor.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor.js:1577:38)
Result.initMarker (/home/camilo/Proyectos/atom-ink/lib/editor/result.coffee:133:33)
new Result (/home/camilo/Proyectos/atom-ink/lib/editor/result.coffee:47:12)
```

**Comment by pfitzseb** [comment]
I think we got rid of this one.

**Comment by carocad** [comment]
true, it doesnt appear on my atom dev any more. Only some minor css things ;)

**Comment by SebastianM-C** [comment]
I got a deprecation warning for this on Atom 1.25 (on Windows) and ink 0.8.3 when using the inline documentation with Ctrl+J Ctrl+D
```
Function.extractParams - <embedded>:77194:20
MarkerLayer.markRange - <embedded>:77840:77
DisplayMarkerLayer.markBufferRange - <embedded>:134571:58
TextEditor.markBufferRange - <embedded>:4447:42
InlineDoc.initMarker - C:\Users\sebastian\.atom\packages\ink\lib\editor\docs.coffee:45:33
new InlineDoc - C:\Users\sebastian\.atom\packages\ink\lib\editor\docs.coffee:15:12
```

**Comment by touchft** [comment]
I got this from atom 1.34, ink 0.9.14. 

Deprecated calls:
Assigning custom properties to a marker when creating/copying it is deprecated. Please, consider storing the custom properties you need in some other object in your package, keyed by the marker's id property.
Report Issue
Function.extractParams - <embedded>:14:61659
MarkerLayer.markRange - <embedded>:14:72468
DisplayMarkerLayer.markBufferRange - <embedded>:14:1096987
TextEditor.markBufferRange - <embedded>:11:28288
InlineDoc.initMarker - /home/ft/.atom/packages/ink/lib/editor/docs.coffee:45:33
new InlineDoc - /home/ft/.atom/packages/ink/lib/editor/docs.coffee:15:12

**Comment by venuur** [comment]
Got this on 1.41.0 on windows and ink 0.11.7

Assigning custom properties to a marker when creating/copying it is deprecated. Please, consider storing the custom properties you need in some other object in your package, keyed by the marker's id property.

Function.extractParams - <embedded>:14:67389
MarkerLayer.markRange - <embedded>:14:78223
DisplayMarkerLayer.markBufferRange - <embedded>:14:1187330
TextEditor.markBufferRange - <embedded>:11:28288
InlineDoc.initMarker - C:\Users\carlm\.atom\packages\ink\lib\editor\docs.coffee:45:33
new InlineDoc - C:\Users\carlm\.atom\packages\ink\lib\editor\docs.coffee:15:12

**Comment by venuur** [comment]
@pfitzseb , seems to still be an issue. Have you considered reopening?
