### ISSUE TITLE
unable to clear block result

### ISSUE THREAD

**Issue by carocad** [JunoLab/atom-ink#74]
For an ink inline-result right clicking it would show an option "clear" which will remove the result from the editor. Nevertheless, this option doesn't show on block results. I guess that this is a bug as I don't see any reason not to be able to remove those results when the user wants it.

Here is a screenshot
![captura de pantalla de 2016-08-25 13-48-10](https://cloud.githubusercontent.com/assets/10408729/17967977/98d3d3ac-6aca-11e6-87c1-cc24de54cd9f.png)

**Comment by pfitzseb** [comment]
Yep, definitely just an oversight. Thanks for reporting this!
