### ISSUE TITLE
Allow search in Console

### ISSUE THREAD

**Issue by jasongilman** [JunoLab/atom-ink#77]
Proto REPL switched to the Atom ink Console and it's been a good improvement in multiple ways over the text editor based repl; performance, better highlighting of only Clojure code but it's also missing some really useful features. One of them is search. It would be a really nice feature to be able to search for text anywhere in the console.

**Comment by pfitzseb** [comment]
I agree that this would be quite the nice feature, but I'm afraid we probably can't use the built-in `find-and-replace` package for this (that seems to be based completly on buffers).
Something like [electron-search-text](https://github.com/nakajmg/electron-search-text) should work though.

**Comment by pfitzseb** [comment]
Done for `console2`.
