### ISSUE TITLE
Run block shortcut 'ctrl-enter' overrides core 'editor:newline-below'

### ISSUE THREAD

**Issue by JohnGurin** [JunoLab/atom-ink#80]

**Comment by pfitzseb** [comment]
So? You can either overwrite that shortcut yourself or disable Juno's keybindings, but this default keybinding is unlikely to change.

**Comment by MikeInnes** [comment]
Of course, suggestions are welcome, but I don't know of another keybinding which will be intuitive to users of other environments (Jupyter, Mathematica etc) without this issue; Atom has a lot of default keybindings.

**Comment by JohnGurin** [comment]
Have not used Jupyter, ect, so can't discuss futher.

In Atom `shift` seems to be vacant. I personally use
`keymap.cson` :

```
'.platform-win32 .item-views > atom-text-editor[data-grammar="source julia"],
 .platform-linux .item-views > atom-text-editor[data-grammar="source julia"]':
  'ctrl-enter': 'editor:newline-below'
  'shift-enter': 'julia-client:run-block'
```
