### ISSUE TITLE
Performance regression with Console output

### ISSUE THREAD

**Issue by jasongilman** [JunoLab/atom-ink#84]
I'm seeing a major performance regression with console output. With Atom ink 0.5.1 the output to the console is speedy and Atom is still responsive even when there is a lot of output. After upgrading to 0.5.3 output to the console seems to lock up Atom and it becomes unresponsive. I ran the developer tools profile and this function was the hotspot: https://github.com/JunoLab/atom-ink/blob/master/lib/console/view.coffee#L33

**Comment by pfitzseb** [comment]
I did some profiling as well (print 100,000 lines as fast we can) and that suggests that https://github.com/JunoLab/atom-ink/blob/master/lib/console/view.coffee#L206 is the problem (as I kinda expected). I'll have a look at this later today.

**Comment by pfitzseb** [comment]
@jasongilman Can you try the [sp/fasterconsole](https://github.com/JunoLab/atom-ink/tree/sp/fasterconsole) branch? I'm seeing a ~tenfold improvement with that, which should be close to what we had before but with the fancy console scrolling (which is now correct, as opposed to my first try at this).
