### ISSUE TITLE
Symbols hard to see with a dark Atom theme

### ISSUE THREAD

**Issue by malmaud** [JunoLab/atom-ink#87]
See the screenshot for an example.
cc @pfitzseb 

<img width="1337" alt="screen shot 2016-10-05 at 8 08 20 am" src="https://cloud.githubusercontent.com/assets/987837/19112525/489a5432-8ad3-11e6-9cbd-c236ceb6bf0a.png">

**Comment by pfitzseb** [comment]
![help](https://cloud.githubusercontent.com/assets/6735977/19323258/75ae1f1e-90bc-11e6-9138-56291094b97d.png)
Depends on the theme, I'd say.

**Comment by pfitzseb** [comment]
Btw, this might be better on the ink master -- care to try?

**Comment by malmaud** [comment]
Hmm, still seems hard to see:
![screen shot 2017-02-20 at 2 31 36 pm](https://cloud.githubusercontent.com/assets/987837/23139256/7ba5cff6-f779-11e6-8ec6-2913b38797f7.png)
