### ISSUE TITLE
output bubble overlays console

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/atom-ink#88]
It looks like some z-ordering issue, where the output bubbles are drawn on top of the console rather than hiding behind.

This is on ink v0.4.4, atom v1.10.2.

![juno z-ordering](https://cloud.githubusercontent.com/assets/734386/19252251/db757592-8f11-11e6-8292-407ec3f4595d.gif)

**Comment by pfitzseb** [comment]
Yeah, that was an issue once upon a time ;) The latest ink version is 0.5.3 though, so try upgrading.
