### ISSUE TITLE
Inline results overlay next line with Material theme

### ISSUE THREAD

**Issue by swt30** [JunoLab/atom-ink#89]
There's an offset box under the inline result bubbles which is masking the text on the next line.

normal behaviour:
![screenshot from 2016-10-14 12-01-05](https://cloud.githubusercontent.com/assets/6207820/19385364/02d1fca4-9206-11e6-8d0a-c268d068c003.png)

Material theme:
![screenshot from 2016-10-14 12-01-31](https://cloud.githubusercontent.com/assets/6207820/19385373/0fdebf36-9206-11e6-97a8-2393e6066004.png)

Don't know if this is Ink or Material's problem but I thought I'd begin by asking here.

**Comment by pfitzseb** [comment]
This has been fixed with https://github.com/JunoLab/atom-ink/commit/04ccf8b2a80e087ea6e1050fbd0fd8b1b049050c, so with the next tagged release you should be good to go.
