### ISSUE TITLE
z-index of unfolded results

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/atom-ink#9]
should be higher than that of folded results, so that this
![zindex](https://cloud.githubusercontent.com/assets/6735977/9731179/b6b9d3ea-561b-11e5-9253-7b9b7153dca0.PNG)
doesn't happen.

**Comment by MikeInnes** [comment]
Yeah that sounds like a good way to handle this issue

**Comment by pfitzseb** [comment]
Slight caveat: What happens when there are multiple overlapping unfolded results? As I've implemented it now, the last evaluated result is on top, but that's unsatisfactory. So, two options:
- Keep track of all folded results and assign them decreasing z-indeces (the one highest up also has the highest z-index)
- give all unfolded results the same z-index and raise them to the foreground by clicking.
  I think I'd prefer the second option, though the first one is arguably more correct.
