### ISSUE TITLE
Console focus behaviour change

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/atom-ink#97]
Clicking on the console tab or `C-J C-O` should always "focus" the last input (in the sense that you can directly start typing), but not scroll there unless you type something in.

See http://discuss.junolab.org/t/some-tips-to-make-users-life-easier/1079/2 for reference.

**Comment by MikeInnes** [comment]
I agree – I'm not sure if focusing directly will scroll as well, but we could probably get the same effect by focusing on any key press.

**Comment by pfitzseb** [comment]
It will, we need to remember the current position and scroll back there. Then attach to the input's `TextEditor` via `onDidChange` with a `_.throttle`d function or something similar.

**Comment by MikeInnes** [comment]
That sounds sensible. Editor changes will probably also scroll it into view right? Overriding that will probably be a good idea when there's a multi-line input and things like that though.

**Comment by pfitzseb** [comment]
No, the editor won't automatically scroll into view when changing it's buffer -- that's why the `onDidChange` stuff will be necessary. Or did you mean something else?

**Comment by MikeInnes** [comment]
Yeah that's what I meant. Changes to input text boxes generally have that behaviour but editors don't for some reason.
